### PR TITLE
readme showing the changes proposal

### PR DESCRIPTION
**Pull request by dio-av**
readme update showing how the changes will impact the use

### CODE REVIEW

**Comment by dio-av** [comment]
Simple approve

**Comment by HectorMalot** [comment]
Hey, this could be interesting, but I'd only include the complete change (i.e. documentation and the actual protocol change. Ideally keeping the existing API intact.) Feel free to add to this PR until done?

**Comment by HectorMalot** [comment]
Hi @dio-av ,

I'm happy to merge into this repo (rather than having 2 separate forks). Would you be able to update the readme in the PR to reflect both clients?

**Comment by dio-av** [comment]
Sure, no problem. I'm still developing the complete historical API in the development branch so there isn't any problem merging.

**Pull request closed without merging**
